apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: piklesfastfood
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: piklesfastfood
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 10
